name: build ubuntu

on:
  push:
    branches: [ next, master ]
  pull_request:
    branches: [ next, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install x11-dev
      run: sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libz-dev libxml2-dev libopengl-dev
    - name: install libtmx
      run: git clone https://github.com/baylej/tmx && mkdir build && cd build && cmake .. && make -j4
    - name: Compile
      run: mkdir build && cd build && cmake .. && make;
