name: build

on:
  push:
    branches: [ raylib-rewrite-because-yes ]
  pull_request:
    branches: [ raylib-rewrite-because-yes ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install emuscription
      run: git clone https://github.com/emscripten-core/emsdk.git; cd emsdk; ./emsdk install latest; ./emsdk activate latest; source ./emsdk_env.sh
    - name: install Raylib
      run: cd emsdk; source ./emsdk_env.sh; cd ..; git clone https://github.com/raysan5/raylib; cd raylib/src; emcc -c rcore.c -Os -Wall -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2; emcc -c rshapes.c -Os -Wall -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2; emcc -c rtextures.c -Os -Wall -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2; emcc -c rtext.c -Os -Wall -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2; emcc -c rmodels.c -Os -Wall -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2; emcc -c utils.c -Os -Wall -DPLATFORM_WEB; emcc -c raudio.c -Os -Wall -DPLATFORM_WEB; emar rcs libraylib.a rcore.o rshapes.o rtextures.o rtext.o rmodels.o utils.o raudio.o;
    - name: Compile
      run: cd emsdk; source ./emsdk_env.sh; cd ..; cd src; emcc -o game.html web-test.c -Os -Wall ../raylib/src/libraylib.a -I. -I../raylib/src/ -L. -L../raylib/src/libraylib.a -s USE_GLFW=3 -s ASYNCIFY --shell-file ../raylib/src/shell.html -DPLATFORM_WEB;
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: |
          assets/
          src/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

