name: build ubuntu

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install x11-dev
      run: sudo apt install libxi-dev libxinerama-dev libxcursor-dev -y
    - name: install Raylib
      run: git clone https://github.com/raysan5/raylib; cd raylib/src; make;
    - name: Compile
      run: make RAYLIB_PATH=./raylib -B;